version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        dependency-type: "production"
        update-types:
        - "minor"
        - "patch"
      group-dependencies:
        dependency-type: "development"
        update-types:
        - "minor"
        - "patch"
    allow:
      - dependency-type: production
      - dependency-type: development
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
