site_name: Griptape Docs
site_url: !ENV READTHEDOCS_CANONICAL_URL
hooks:
  - docs/plugins/swagger_ui_plugin.py
strict: true
plugins:
  - glightbox
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["griptape"]
          options:
            show_if_no_docstring: true
            heading_level: 3
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
copyright: "&copy; Griptape, Inc."
extra_css:
  - assets/css/extra.css
  - assets/css/code_select.css
  - assets/css/mkdocstrings.css
  - assets/css/swagger-ui.css
extra_javascript:
  - assets/scripts/swagger-ui-bundle.js
  - assets/scripts/swagger-ui-standalone-preset.js
extra:
  analytics:
    provider: google
    property: G-QM8EDPSCB6
  social:
    - icon: fontawesome/solid/house
      link: https://www.griptape.ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/gnWRz88eym
    - icon: fontawesome/brands/github
      link: https://github.com/griptape-ai/griptape/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/griptape/
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/img/griptape-mark-square-light.svg
  palette:
    scheme: slate
    primary: black
    accent: deep orange
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - announce.dismiss
    - toc.follow
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - tables
  - def_list
  - footnotes
nav:
  - Home:
      - Overview: "index.md"
      - Contributing: "contributing.md"
  - Cloud:
      - Overview: "griptape-cloud/index.md"
      - Data Sources:
          - Create a Data Source: "griptape-cloud/data-sources/create-data-source.md"
          - Refreshing Your Data: "griptape-cloud/data-sources/refresh-data.md"
      - Knowledge Bases:
          - Create a Knowledge Base: "griptape-cloud/knowledge-bases/create-knowledge-base.md"
          - Accessing Your Data: "griptape-cloud/knowledge-bases/accessing-data.md"
      - Structures:
          - Create a Structure: "griptape-cloud/structures/create-structure.md"
          - Structure Config YAML: "griptape-cloud/structures/structure-config.md"
          - Running Your Structure: "griptape-cloud/structures/run-structure.md"
      - Cloud API:
          - API Reference: "griptape-cloud/api/api-reference.md"
  - Framework:
      - Overview: "griptape-framework/index.md"
      - Structures:
          - Agents: "griptape-framework/structures/agents.md"
          - Pipelines: "griptape-framework/structures/pipelines.md"
          - Workflows: "griptape-framework/structures/workflows.md"
          - Tasks: "griptape-framework/structures/tasks.md"
          - Task Memory and Off Prompt: "griptape-framework/structures/task-memory.md"
          - Conversation Memory: "griptape-framework/structures/conversation-memory.md"
          - Rulesets: "griptape-framework/structures/rulesets.md"
          - Configs: "griptape-framework/structures/configs.md"
          - Observability: "griptape-framework/structures/observability.md"
      - Tools:
          - Overview: "griptape-framework/tools/index.md"
          - Building Custom Tools: "griptape-tools/custom-tools/index.md"
      - Engines:
          - RAG Engines: "griptape-framework/engines/rag-engines.md"
          - Image Query Engines: "griptape-framework/engines/image-query-engines.md"
          - Extraction Engines: "griptape-framework/engines/extraction-engines.md"
          - Summary Engines: "griptape-framework/engines/summary-engines.md"
          - Image Generation Engines: "griptape-framework/engines/image-generation-engines.md"
          - Audio Engines: "griptape-framework/engines/audio-engines.md"
      - Drivers:
          - Prompt Drivers: "griptape-framework/drivers/prompt-drivers.md"
          - Embedding Drivers: "griptape-framework/drivers/embedding-drivers.md"
          - Vector Store Drivers: "griptape-framework/drivers/vector-store-drivers.md"
          - Image Generation Drivers: "griptape-framework/drivers/image-generation-drivers.md"
          - SQL Drivers: "griptape-framework/drivers/sql-drivers.md"
          - Image Query Drivers: "griptape-framework/drivers/image-query-drivers.md"
          - Web Scraper Drivers: "griptape-framework/drivers/web-scraper-drivers.md"
          - Conversation Memory Drivers: "griptape-framework/drivers/conversation-memory-drivers.md"
          - Event Listener Drivers: "griptape-framework/drivers/event-listener-drivers.md"
          - Structure Run Drivers: "griptape-framework/drivers/structure-run-drivers.md"
          - Text to Speech Drivers: "griptape-framework/drivers/text-to-speech-drivers.md"
          - Audio Transcription Drivers: "griptape-framework/drivers/audio-transcription-drivers.md"
          - Web Search Drivers: "griptape-framework/drivers/web-search-drivers.md"
          - Observability Drivers: "griptape-framework/drivers/observability-drivers.md"
      - Data:
          - Overview: "griptape-framework/data/index.md"
          - Artifacts: "griptape-framework/data/artifacts.md"
          - Chunkers: "griptape-framework/data/chunkers.md"
          - Loaders: "griptape-framework/data/loaders.md"
      - Misc:
          - Events: "griptape-framework/misc/events.md"
          - Tokenizers: "griptape-framework/misc/tokenizers.md"
  - Tools:
      - Overview: "griptape-tools/index.md"
      - Official Tools:
          - Aws Iam: "griptape-tools/official-tools/aws-iam-tool.md"
          - Aws S3: "griptape-tools/official-tools/aws-s3-tool.md"
          - Calculator: "griptape-tools/official-tools/calculator-tool.md"
          - Computer: "griptape-tools/official-tools/computer-tool.md"
          - Date Time: "griptape-tools/official-tools/date-time-tool.md"
          - Email: "griptape-tools/official-tools/email-tool.md"
          - File Manager: "griptape-tools/official-tools/file-manager-tool.md"
          - Google Calendar: "griptape-tools/official-tools/google-calendar-tool.md"
          - Google Gmail: "griptape-tools/official-tools/google-gmail-tool.md"
          - Google Drive: "griptape-tools/official-tools/google-drive-tool.md"
          - Google Docs: "griptape-tools/official-tools/google-docs-tool.md"
          - Structure Run Client: "griptape-tools/official-tools/structure-run-tool.md"
          - Open Weather: "griptape-tools/official-tools/openweather-tool.md"
          - Rest Api Client: "griptape-tools/official-tools/rest-api-tool.md"
          - Sql: "griptape-tools/official-tools/sql-tool.md"
          - Vector Store Tool: "griptape-tools/official-tools/vector-store-tool.md"
          - Web Scraper: "griptape-tools/official-tools/web-scraper-tool.md"
          - Web Search: "griptape-tools/official-tools/web-search-tool.md"
          - Prompt Image Generation: "griptape-tools/official-tools/prompt-image-generation-tool.md"
          - Variation ImageGeneration: "griptape-tools/official-tools/variation-image-generation-tool.md"
          - Inpainting ImageGeneration: "griptape-tools/official-tools/inpainting-image-generation-tool.md"
          - Outpainting ImageGeneration: "griptape-tools/official-tools/outpainting-image-generation-tool.md"
          - Image Query: "griptape-tools/official-tools/image-query-tool.md"
          - Text To Speech: "griptape-tools/official-tools/text-to-speech-tool.md"
          - Audio Transcription: "griptape-tools/official-tools/audio-transcription-tool.md"
          - Griptape Cloud Knowledge Base: "griptape-tools/official-tools/griptape-cloud-knowledge-base-tool.md"
          - Rag: "griptape-tools/official-tools/rag-tool.md"
          - Extraction: "griptape-tools/official-tools/extraction-tool.md"
          - Query: "griptape-tools/official-tools/query-tool.md"
          - Prompt Summary: "griptape-tools/official-tools/prompt-summary-tool.md"
      - Custom Tools:
          - Building Custom Tools: "griptape-tools/custom-tools/index.md"
  - Recipes:
      - Overview: "examples/index.md"
      - Agents:
          - Talk to Redshift: "examples/talk-to-redshift.md"
          - Talk to a Webpage: "examples/talk-to-a-webpage.md"
          - Talk to a PDF: "examples/talk-to-a-pdf.md"
          - Talk to a Video: "examples/talk-to-a-video.md"
          - Multi Agent Workflows: "examples/multi-agent-workflow.md"
          - Shared Memory Between Agents: "examples/multiple-agent-shared-memory.md"
          - Chat Sessions with Amazon DynamoDB: "examples/amazon-dynamodb-sessions.md"
      - Data:
          - Load and Query Pinecone: "examples/load-and-query-pinecone.md"
          - Load and Query Marqo: "examples/load-query-and-chat-marqo.md"
          - Query a Webpage: "examples/query-webpage.md"
          - RAG with Astra DB vector store: "examples/query-webpage-astra-db.md"
  - Reference Guide: "reference/"
  - Trade School: "https://learn.griptape.ai"
